### PR TITLE
Protect against related field issue

### LINKED ISSUE #24: GetCapabilities does not work with dotted model_attribute value
If a FeatureField has reference to a different model via FK reference, GetCapabilities query is not working.
eg.

`FeatureField(
        "not_working",
        model_attribute="some_fk.field_name",
        abstract="does not work",
    )`

Result from eg. http://localhost:8000/wfs/?SERVICE=WFS&VERSION=2.0.0&REQUEST=GetCapabilities
Now would be 500 internal server error.
Reason would be that "<feature_type> has no attribute field_name"

This is because FeatureType.get_bounding_box function uses self.get_query_set() that does not check any feature relations.

Suggested fix:
Change function FeatureType.get_bounding_box not to use get_query_set() as such but add a .only(self.geometry_field.name)

so line:
`bbox = self.get_queryset().aggregate(a=Extent(geo_expression))["a"]`
to:
`bbox = self.get_queryset().only(self.geometry_field.name).aggregate(a=Extent(geo_expression))["a"]`
or even:
`bbox = self.queryset.only(self.geometry_field.name).aggregate(a=Extent(geo_expression))["a"]`

I am not so familiar with the codebase that really not sure if this is the way to go here, maybe someone who actually is doing dev on this will do the actual fix in a different way. Atleast this way there would be no need for any prefetches.

### PR DESCRIPTION
**Pull request by sposs**
Hopefully fixes #24

### CODE REVIEW

**Comment by vdboor** [comment]
Hi! Thanks for offering this fix. It looks like a good first start. I wonder, would it be possible to have some kind of unit test or example for this? That would make it easier to guarantee this is the right fix. TIA!

**Comment by sposs** [comment]
I've added a test that fails if the patch is not added. Moreover, I see that the previous test cases passed because the feature Restaurant has a field 'name' and the city also has a field 'name', and so there is collision between the field names. I've thus added a field that does not exist in the Restaurant to ensure the resolution of related.

**Comment by sposs** [comment]
Last commit needed because your pre-commit hooks are a little too strict on the line lengths...

**Review by vdboor — APPROVED** [review]
Sorry I missed this one, looks good! Thanks!

**Comment by vdboor** [comment]
I've merged this manually with rebasing (to resolve conflicts). Your changes are in 729467821b3d6e3f8e59e5dd686b7001e03f8eb1 and are released as 1.4.1 :-) 

I've updated our pre-commit-config too in main. It's quite odd that it triggered for you, as `pre-commit run -a` doesn't report anything here.

**Pull request closed without merging**
